// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {main} from '../models';

export function ClearAvatar():Promise<store.User>;

export function CurrentUser():Promise<store.User>;

export function GetAppVersion():Promise<string>;

export function GetBootLogs():Promise<Array<string>>;

export function Login(arg1:string,arg2:string):Promise<store.User>;

export function Logout():Promise<void>;

export function Ping():Promise<main.SidecarStatus>;

export function Register(arg1:string,arg2:string,arg3:string):Promise<store.User>;

export function RevealMainWindow():Promise<void>;

export function SetAvatar(arg1:string):Promise<store.User>;

export function UpdateDisplayName(arg1:string):Promise<store.User>;
