// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearAvatar() {
  return window['go']['main']['App']['ClearAvatar']();
}

export function CurrentUser() {
  return window['go']['main']['App']['CurrentUser']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetBootLogs() {
  return window['go']['main']['App']['GetBootLogs']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}

export function Register(arg1, arg2, arg3) {
  return window['go']['main']['App']['Register'](arg1, arg2, arg3);
}

export function RevealMainWindow() {
  return window['go']['main']['App']['RevealMainWindow']();
}

export function SetAvatar(arg1) {
  return window['go']['main']['App']['SetAvatar'](arg1);
}

export function UpdateDisplayName(arg1) {
  return window['go']['main']['App']['UpdateDisplayName'](arg1);
}
