// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetBootLogs() {
  return window['go']['main']['App']['GetBootLogs']();
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}

export function RevealMainWindow() {
  return window['go']['main']['App']['RevealMainWindow']();
}
