// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAppVersion():Promise<string>;

export function GetBootLogs():Promise<Array<string>>;

export function Ping():Promise<main.SidecarStatus>;

export function RevealMainWindow():Promise<void>;
